/* generated by jimc — do not edit */
#define JIM_PANIC_ABORT 1
/* ==== jim runtime v0 ====
 * Embedded verbatim at the top of every generated translation unit.
 * Memory model: bump arena, freed in one sweep at exit (jim has no free()).
 * Every rt_* function backs a compiler intrinsic (see docs/DESIGN.md §6).
 */
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifndef JIM_PANIC_ABORT
#include <setjmp.h> /* try/catch unwinding; omitted in panic=abort builds */
#endif
#include <math.h>
#include <errno.h>

typedef struct {
    const char* ptr;
    int64_t len;
} jim_str;

static jim_str rt_str_lit(const char* p, int64_t n) {
    jim_str s;
    s.ptr = p;
    s.len = n;
    return s;
}

/* ---- arena ---- */

typedef struct rt_block {
    struct rt_block* next;
    size_t used;
    size_t cap;
} rt_block;

static rt_block* rt_arena = NULL;

static void rt_oom(void) {
    fputs("jim: out of memory\n", stderr);
    exit(1);
}

static void* rt_arena_alloc(size_t n) {
    n = (n + 7u) & ~(size_t)7u; /* 8-byte alignment; block payload starts 8-aligned */
    if (rt_arena == NULL || rt_arena->used + n > rt_arena->cap) {
        size_t cap = n > 65536 ? n : 65536;
        rt_block* b = (rt_block*)malloc(sizeof(rt_block) + cap);
        if (b == NULL) rt_oom();
        b->next = rt_arena;
        b->used = 0;
        b->cap = cap;
        rt_arena = b;
    }
    void* p = (char*)(rt_arena + 1) + rt_arena->used;
    rt_arena->used += n;
    return p;
}

static void rt_init(void) {}

static void rt_shutdown(void) {
    rt_block* b = rt_arena;
    while (b != NULL) {
        rt_block* next = b->next;
        free(b);
        b = next;
    }
    rt_arena = NULL;
}

/* ---- panics & try/catch ----
 * Panics unwind to the innermost try (setjmp/longjmp handler stack);
 * uncaught, they print and exit(1).
 *
 * In panic=abort builds (JIM_PANIC_ABORT — used by the browser playground,
 * where wasm setjmp/longjmp isn't portably available) there is no handler
 * stack: every panic prints and exits, and codegen omits try/catch handlers.
 */

#ifndef JIM_PANIC_ABORT
typedef struct rt_handler {
    jmp_buf buf;
    struct rt_handler* prev;
    int frame_top; /* stack-trace depth at try entry (longjmp restores it) */
} rt_handler;

static rt_handler* rt_handlers = NULL;
static jim_str rt_current_exc;
#endif

/* ---- stack traces ----
 * Debug builds (`jimc run`, `jimc build --debug`) maintain a shadow stack:
 * push/pop per jim function, plus a line store before each call. Release
 * builds emit none of these calls — rt_frame_top stays 0 and panics print
 * exactly as before. The frames beyond the cap are counted, not stored.
 */

typedef struct {
    const char* file;
    const char* fn;
    int32_t line;
} rt_frame;

#define RT_MAX_FRAMES 256
static rt_frame rt_frames[RT_MAX_FRAMES];
static int rt_frame_top = 0;

static void rt_push_frame(const char* file, const char* fn) {
    if (rt_frame_top < RT_MAX_FRAMES) {
        rt_frames[rt_frame_top].file = file;
        rt_frames[rt_frame_top].fn = fn;
        rt_frames[rt_frame_top].line = 0;
    }
    rt_frame_top++;
}

static void rt_pop_frame(void) {
    if (rt_frame_top > 0) rt_frame_top--;
}

static void rt_frame_line(int32_t line) {
    if (rt_frame_top > 0 && rt_frame_top <= RT_MAX_FRAMES) {
        rt_frames[rt_frame_top - 1].line = line;
    }
}

static void rt_print_trace(void) {
    int shown = rt_frame_top < RT_MAX_FRAMES ? rt_frame_top : RT_MAX_FRAMES;
    fputs("stack trace (most recent call first):\n", stderr);
    if (rt_frame_top > RT_MAX_FRAMES) {
        fprintf(stderr, "  ... %d deeper frame(s) not recorded\n", rt_frame_top - RT_MAX_FRAMES);
    }
    for (int i = shown - 1; i >= 0; i--) {
        fprintf(stderr, "  at %s (%s:%d)\n", rt_frames[i].fn, rt_frames[i].file, (int)rt_frames[i].line);
    }
}

static void rt_panic(jim_str msg) {
#ifndef JIM_PANIC_ABORT
    if (rt_handlers != NULL) {
        rt_current_exc = msg;
        rt_handler* h = rt_handlers;
        rt_handlers = h->prev;        /* pop before the jump */
        rt_frame_top = h->frame_top;  /* unwind the shadow stack too */
        longjmp(h->buf, 1);
    }
#endif
    fputs("jim panic: ", stderr);
    fwrite(msg.ptr, 1, (size_t)msg.len, stderr);
    fputc('\n', stderr);
    if (rt_frame_top > 0) rt_print_trace();
    exit(1);
}

static void rt_panic_cstr(const char* msg) {
    rt_panic(rt_str_lit(msg, (int64_t)strlen(msg)));
}

/* @panic from jim code carries its compile-time location. Caught panics keep
 * the bare message (an Exception's repr IS its message); only the fatal,
 * uncaught printout shows the location. In debug builds the shadow stack's
 * innermost frame already holds this location, so the full trace replaces
 * the single-line form. */
static void rt_panic_at(jim_str msg, const char* file, int line, const char* fn) {
#ifndef JIM_PANIC_ABORT
    if (rt_handlers != NULL) {
        rt_panic(msg);
    }
#endif
    fputs("jim panic: ", stderr);
    fwrite(msg.ptr, 1, (size_t)msg.len, stderr);
    fputc('\n', stderr);
    if (rt_frame_top > 0) {
        rt_print_trace();
    } else {
        fprintf(stderr, "  at %s:%d (in %s)\n", file, line, fn);
    }
    exit(1);
}

/* the message of the exception being handled (Exception's repr IS the message) */
static jim_str rt_exc_msg(jim_str e) { return e; }

/* optional reference types are nullable pointers; using None panics */
static void* rt_nonnull(void* p, const char* tyname) {
    if (p == NULL) {
        char buf[160];
        int n = snprintf(buf, sizeof buf, "used a None value where %s was needed", tyname);
        char* m = (char*)rt_arena_alloc((size_t)n);
        memcpy(m, buf, (size_t)n);
        rt_panic(rt_str_lit(m, n));
    }
    return p;
}

/* ---- optionals (T?) ----
 * A T? is a tagged value. Using a None where a value is needed panics
 * (later interceptable by try/catch).
 */

typedef struct { bool has; int64_t value; } jim_opt_i64;
typedef struct { bool has; double value; } jim_opt_f64;
typedef struct { bool has; bool value; } jim_opt_bool;
typedef struct { bool has; uint8_t value; } jim_opt_char;
typedef struct { bool has; jim_str value; } jim_opt_str;

#define JIM_DEFINE_OPT(sfx, T, tyname) \
    static jim_opt_##sfx rt_opt_##sfx##_some(T v) { \
        jim_opt_##sfx o; o.has = true; o.value = v; return o; \
    } \
    static jim_opt_##sfx rt_opt_##sfx##_none(void) { \
        jim_opt_##sfx o; memset(&o, 0, sizeof o); o.has = false; return o; \
    } \
    static T rt_opt_##sfx##_get(jim_opt_##sfx o) { \
        if (!o.has) rt_panic_cstr("used a None value where " tyname " was needed"); \
        return o.value; \
    } \
    static bool rt_opt_##sfx##_has(jim_opt_##sfx o) { return o.has; }

JIM_DEFINE_OPT(i64, int64_t, "Integer")
JIM_DEFINE_OPT(f64, double, "Float")
JIM_DEFINE_OPT(bool, bool, "Bool")
JIM_DEFINE_OPT(char, uint8_t, "Char")
JIM_DEFINE_OPT(str, jim_str, "String")

/* ---- RawBuffer<T> ----
 * Unchecked raw storage for the std library's Array/Vector. Bounds checks
 * and growth logic live in jim code, not here. The compiler emits one
 * JIM_DEFINE_BUF(sfx, T) line per element type in use.
 */
#define JIM_DEFINE_BUF(sfx, T) \
    typedef struct { T* data; int64_t cap; } jim_buf_##sfx; \
    static jim_buf_##sfx jim_buf_##sfx##_alloc(int64_t n) { \
        jim_buf_##sfx b; \
        if (n < 0) n = 0; \
        b.data = (T*)rt_arena_alloc((size_t)n * sizeof(T)); \
        b.cap = n; \
        return b; \
    } \
    static T jim_buf_##sfx##_get(jim_buf_##sfx b, int64_t i) { return b.data[i]; } \
    static void jim_buf_##sfx##_set(jim_buf_##sfx b, int64_t i, T v) { b.data[i] = v; } \
    static int64_t jim_buf_##sfx##_capacity(jim_buf_##sfx b) { return b.cap; }

/* ---- Integer (checked 64-bit arithmetic) ---- */

static int64_t rt_i64_add(int64_t a, int64_t b) {
    int64_t r;
    if (__builtin_add_overflow(a, b, &r)) rt_panic_cstr("Integer overflow in addition");
    return r;
}

static int64_t rt_i64_sub(int64_t a, int64_t b) {
    int64_t r;
    if (__builtin_sub_overflow(a, b, &r)) rt_panic_cstr("Integer overflow in subtraction");
    return r;
}

static int64_t rt_i64_mul(int64_t a, int64_t b) {
    int64_t r;
    if (__builtin_mul_overflow(a, b, &r)) rt_panic_cstr("Integer overflow in multiplication");
    return r;
}

static int64_t rt_i64_divtrunc(int64_t a, int64_t b) {
    if (b == 0) rt_panic_cstr("Integer division by zero");
    if (a == INT64_MIN && b == -1) rt_panic_cstr("Integer overflow in division");
    return a / b;
}

static int64_t rt_i64_mod(int64_t a, int64_t b) {
    if (b == 0) rt_panic_cstr("Integer modulo by zero");
    if (a == INT64_MIN && b == -1) return 0;
    return a % b;
}

static int64_t rt_i64_neg(int64_t a) {
    if (a == INT64_MIN) rt_panic_cstr("Integer overflow in negation");
    return -a;
}

static bool rt_i64_eq(int64_t a, int64_t b) { return a == b; }
static bool rt_i64_lt(int64_t a, int64_t b) { return a < b; }
static double rt_i64_to_f64(int64_t a) { return (double)a; }

static jim_str rt_i64_to_string(int64_t v) {
    char buf[32];
    int n = snprintf(buf, sizeof buf, "%lld", (long long)v);
    char* p = (char*)rt_arena_alloc((size_t)n);
    memcpy(p, buf, (size_t)n);
    return rt_str_lit(p, n);
}

/* ---- Float ---- */

static double rt_f64_add(double a, double b) { return a + b; }
static double rt_f64_sub(double a, double b) { return a - b; }
static double rt_f64_mul(double a, double b) { return a * b; }
static double rt_f64_div(double a, double b) { return a / b; } /* IEEE: inf/nan */
static double rt_f64_neg(double a) { return -a; }
static bool rt_f64_eq(double a, double b) { return a == b; }
static bool rt_f64_lt(double a, double b) { return a < b; }

static int64_t rt_f64_to_i64(double v) {
    if (v != v) rt_panic_cstr("cannot convert NaN to Integer");
    if (v >= 9223372036854775808.0 || v < -9223372036854775808.0)
        rt_panic_cstr("Float out of Integer range");
    return (int64_t)v; /* truncates toward zero */
}

static jim_str rt_f64_to_string(double v) {
    char buf[64];
    int n = snprintf(buf, sizeof buf, "%.15g", v);
    /* make whole doubles read as Floats: 3 -> 3.0 */
    bool needs_point = true;
    for (int i = 0; i < n; i++) {
        char c = buf[i];
        if (c == '.' || c == 'e' || c == 'E' || c == 'n' || c == 'i') {
            needs_point = false;
            break;
        }
    }
    if (needs_point && n < (int)sizeof buf - 2) {
        buf[n++] = '.';
        buf[n++] = '0';
    }
    char* p = (char*)rt_arena_alloc((size_t)n);
    memcpy(p, buf, (size_t)n);
    return rt_str_lit(p, n);
}

/* ---- Bool / Char (a Char is one byte, 0-255) ---- */

static bool rt_bool_eq(bool a, bool b) { return a == b; }
static bool rt_char_eq(uint8_t a, uint8_t b) { return a == b; }
static bool rt_char_lt(uint8_t a, uint8_t b) { return a < b; }
static int64_t rt_char_to_i64(uint8_t c) { return (int64_t)c; }

static uint8_t rt_i64_to_char(int64_t v) {
    if (v < 0 || v > 255) rt_panic_cstr("Integer out of Char range (0-255)");
    return (uint8_t)v;
}

static jim_str rt_char_to_string(uint8_t c) {
    char* p = (char*)rt_arena_alloc(1);
    p[0] = (char)c;
    return rt_str_lit(p, 1);
}

/* ---- String ---- */

static int64_t rt_str_len(jim_str s) { return s.len; }

/* unchecked byte read — the std library's String.get adds the bounds check */
static uint8_t rt_str_byte(jim_str s, int64_t i) { return (uint8_t)s.ptr[i]; }

static jim_str rt_str_concat(jim_str a, jim_str b) {
    int64_t n = a.len + b.len;
    char* p = (char*)rt_arena_alloc((size_t)n);
    if (a.len > 0) memcpy(p, a.ptr, (size_t)a.len);
    if (b.len > 0) memcpy(p + a.len, b.ptr, (size_t)b.len);
    return rt_str_lit(p, n);
}

static bool rt_str_eq(jim_str a, jim_str b) {
    if (a.len != b.len) return false;
    if (a.len == 0) return true;
    return memcmp(a.ptr, b.ptr, (size_t)a.len) == 0;
}

static bool rt_str_lt(jim_str a, jim_str b) {
    int64_t n = a.len < b.len ? a.len : b.len;
    if (n > 0) {
        int c = memcmp(a.ptr, b.ptr, (size_t)n);
        if (c != 0) return c < 0;
    }
    return a.len < b.len;
}

/* zero-copy substring view — strings are immutable, so a slice can alias the
 * original bytes. Unchecked: the std library adds the bounds checks. */
static jim_str rt_str_slice(jim_str s, int64_t start, int64_t len) {
    return rt_str_lit(s.ptr + start, len);
}

/* one copy out of raw byte storage — the string-builder escape hatch */
static jim_str rt_str_from_bytes(const uint8_t* p, int64_t len) {
    if (len <= 0) return rt_str_lit("", 0);
    char* q = (char*)rt_arena_alloc((size_t)len);
    memcpy(q, p, (size_t)len);
    return rt_str_lit(q, len);
}

/* Strict decimal parse: optional sign, digits, nothing else. None otherwise
 * (including on overflow). */
static jim_opt_i64 rt_str_to_i64(jim_str s) {
    char buf[24]; /* sign + 19 digits + NUL fits every int64 */
    if (s.len <= 0 || s.len >= (int64_t)sizeof buf) return rt_opt_i64_none();
    char c0 = s.ptr[0];
    if (c0 != '+' && c0 != '-' && (c0 < '0' || c0 > '9')) return rt_opt_i64_none();
    memcpy(buf, s.ptr, (size_t)s.len);
    buf[s.len] = 0;
    errno = 0;
    char* end = NULL;
    long long v = strtoll(buf, &end, 10);
    if (errno != 0 || end != buf + s.len) return rt_opt_i64_none();
    return rt_opt_i64_some((int64_t)v);
}

/* Strict decimal/scientific parse ("2.5", "-1e9"). None otherwise. */
static jim_opt_f64 rt_str_to_f64(jim_str s) {
    char buf[64];
    if (s.len <= 0 || s.len >= (int64_t)sizeof buf) return rt_opt_f64_none();
    char c0 = s.ptr[0];
    if (c0 != '+' && c0 != '-' && c0 != '.' && (c0 < '0' || c0 > '9')) return rt_opt_f64_none();
    memcpy(buf, s.ptr, (size_t)s.len);
    buf[s.len] = 0;
    errno = 0;
    char* end = NULL;
    double v = strtod(buf, &end);
    if (errno != 0 || end != buf + s.len) return rt_opt_f64_none();
    return rt_opt_f64_some(v);
}

/* ---- Float math (libm; IEEE-permissive — domain errors yield nan/inf,
 * policy such as "None for sqrt of a negative" belongs in jim code) ---- */

static double rt_f64_sqrt(double x) { return sqrt(x); }
static double rt_f64_cbrt(double x) { return cbrt(x); }
static double rt_f64_hypot(double x, double y) { return hypot(x, y); }
static double rt_f64_exp(double x) { return exp(x); }
static double rt_f64_log(double x) { return log(x); }
static double rt_f64_log2(double x) { return log2(x); }
static double rt_f64_log10(double x) { return log10(x); }
static double rt_f64_sin(double x) { return sin(x); }
static double rt_f64_cos(double x) { return cos(x); }
static double rt_f64_tan(double x) { return tan(x); }
static double rt_f64_asin(double x) { return asin(x); }
static double rt_f64_acos(double x) { return acos(x); }
static double rt_f64_atan(double x) { return atan(x); }
static double rt_f64_atan2(double y, double x) { return atan2(y, x); }
static double rt_f64_fmod(double x, double y) { return fmod(x, y); }
static double rt_f64_pow(double x, double y) { return pow(x, y); }
static bool rt_f64_is_nan(double x) { return x != x; }
static bool rt_f64_is_inf(double x) { return isinf(x) != 0; }
static bool rt_f64_is_finite(double x) { return isfinite(x) != 0; }

/* ---- Integer bit operations ---- */

static int64_t rt_i64_and(int64_t a, int64_t b) { return a & b; }
static int64_t rt_i64_or(int64_t a, int64_t b) { return a | b; }
static int64_t rt_i64_xor(int64_t a, int64_t b) { return a ^ b; }
static int64_t rt_i64_not(int64_t a) { return ~a; }

static int64_t rt_i64_shl(int64_t a, int64_t b) {
    if (b < 0 || b > 63) rt_panic_cstr("shift amount out of range (0-63)");
    return (int64_t)((uint64_t)a << (uint64_t)b); /* defined: overflow bits drop */
}

static int64_t rt_i64_shr(int64_t a, int64_t b) {
    if (b < 0 || b > 63) rt_panic_cstr("shift amount out of range (0-63)");
    return a >> b; /* arithmetic: the sign is preserved */
}

/* ---- io ---- */

static void rt_print_string(jim_str s) {
    fwrite(s.ptr, 1, (size_t)s.len, stdout);
    fputc('\n', stdout);
}

static void rt_print_err(jim_str s) {
    fwrite(s.ptr, 1, (size_t)s.len, stderr);
    fputc('\n', stderr);
}

/* file paths need NUL termination for the C library */
static char* rt_cstr(jim_str s) {
    char* p = (char*)rt_arena_alloc((size_t)s.len + 1);
    if (s.len > 0) memcpy(p, s.ptr, (size_t)s.len);
    p[s.len] = 0;
    return p;
}

/* one line from stdin without the newline (CRLF handled); None at EOF */
static jim_opt_str rt_read_line(void) {
    size_t cap = 128, n = 0;
    char* tmp = (char*)malloc(cap);
    if (tmp == NULL) rt_oom();
    int ch;
    while ((ch = fgetc(stdin)) != EOF && ch != '\n') {
        if (n == cap) {
            cap *= 2;
            char* t2 = (char*)realloc(tmp, cap);
            if (t2 == NULL) { free(tmp); rt_oom(); }
            tmp = t2;
        }
        tmp[n++] = (char)ch;
    }
    if (ch == EOF && n == 0) {
        free(tmp);
        return rt_opt_str_none();
    }
    if (n > 0 && tmp[n - 1] == '\r') n--; /* Windows CRLF */
    char* p = (char*)rt_arena_alloc(n);
    memcpy(p, tmp, n);
    free(tmp);
    return rt_opt_str_some(rt_str_lit(p, (int64_t)n));
}

static jim_opt_str rt_read_file(jim_str path) {
    FILE* f = fopen(rt_cstr(path), "rb");
    if (f == NULL) return rt_opt_str_none();
    if (fseek(f, 0, SEEK_END) != 0) { fclose(f); return rt_opt_str_none(); }
    long sz = ftell(f);
    if (sz < 0) { fclose(f); return rt_opt_str_none(); }
    if (fseek(f, 0, SEEK_SET) != 0) { fclose(f); return rt_opt_str_none(); }
    char* p = (char*)rt_arena_alloc((size_t)sz);
    size_t got = sz > 0 ? fread(p, 1, (size_t)sz, f) : 0;
    fclose(f);
    if (got != (size_t)sz) return rt_opt_str_none();
    return rt_opt_str_some(rt_str_lit(p, (int64_t)sz));
}

static jim_opt_i64 rt_file_write_mode(jim_str path, jim_str content, const char* mode) {
    FILE* f = fopen(rt_cstr(path), mode);
    if (f == NULL) return rt_opt_i64_none();
    size_t got = content.len > 0 ? fwrite(content.ptr, 1, (size_t)content.len, f) : 0;
    int close_err = fclose(f);
    if (got != (size_t)content.len || close_err != 0) return rt_opt_i64_none();
    return rt_opt_i64_some((int64_t)got);
}

static jim_opt_i64 rt_write_file(jim_str path, jim_str content) {
    return rt_file_write_mode(path, content, "wb");
}

static jim_opt_i64 rt_append_file(jim_str path, jim_str content) {
    return rt_file_write_mode(path, content, "ab");
}

static bool rt_file_exists(jim_str path) {
    FILE* f = fopen(rt_cstr(path), "rb");
    if (f != NULL) {
        fclose(f);
        return true;
    }
    return false;
}

/* ==== jim classes ==== */

typedef struct jim_c_Array_Integer_ jim_c_Array_Integer_;
typedef struct jim_c_Vector_Integer_ jim_c_Vector_Integer_;
typedef struct jim_c_Vector_String_ jim_c_Vector_String_;
typedef struct jim_c_Array_String_ jim_c_Array_String_;

JIM_DEFINE_BUF(Integer, int64_t)
JIM_DEFINE_BUF(String, jim_str)

struct jim_c_Array_Integer_ {
    jim_buf_Integer f_buffer;
    int64_t f_size;
};

struct jim_c_Vector_Integer_ {
    jim_buf_Integer f_buffer;
    int64_t f_idx;
};

struct jim_c_Vector_String_ {
    jim_buf_String f_buffer;
    int64_t f_idx;
};

struct jim_c_Array_String_ {
    jim_buf_String f_buffer;
    int64_t f_size;
};

/* ==== jim program ==== */

static jim_str jim_m_Exception_msg(jim_str jl_this);
static bool jim_m_Char_equals(uint8_t jl_this, uint8_t jl_other);
static bool jim_m_Char_less_than(uint8_t jl_this, uint8_t jl_other);
static jim_str jim_m_Char_to_string(uint8_t jl_this);
static int64_t jim_m_Char_to_integer(uint8_t jl_this);
static uint8_t jim_m_Char_to_upper(uint8_t jl_this);
static uint8_t jim_m_Char_to_lower(uint8_t jl_this);
static jim_opt_bool jim_m_Char_is_alpha(uint8_t jl_this);
static jim_opt_bool jim_m_Char_is_digit(uint8_t jl_this);
static jim_opt_bool jim_m_Char_is_alnum(uint8_t jl_this);
static jim_opt_bool jim_m_Char_is_upper(uint8_t jl_this);
static jim_opt_bool jim_m_Char_is_lower(uint8_t jl_this);
static jim_opt_bool jim_m_Char_is_space(uint8_t jl_this);
static jim_opt_bool jim_m_Char_is_punct(uint8_t jl_this);
static jim_opt_bool jim_m_Char_is_ascii_printable(uint8_t jl_this);
static jim_opt_i64 jim_m_Char_digit_value(uint8_t jl_this);
static bool jim_m_Bool_equals(bool jl_this, bool jl_other);
static jim_str jim_m_Bool_to_string(bool jl_this);
static int64_t jim_m_Bool_to_integer(bool jl_this);
static double jim_m_Float_plus(double jl_this, double jl_other);
static double jim_m_Float_minus(double jl_this, double jl_other);
static double jim_m_Float_times(double jl_this, double jl_other);
static double jim_m_Float_divide(double jl_this, double jl_other);
static double jim_m_Float_negate(double jl_this);
static bool jim_m_Float_equals(double jl_this, double jl_other);
static bool jim_m_Float_less_than(double jl_this, double jl_other);
static int64_t jim_m_Float_to_integer(double jl_this);
static jim_str jim_m_Float_to_string(double jl_this);
static jim_opt_f64 jim_m_Float_abs(double jl_this);
static jim_opt_f64 jim_m_Float_sign(double jl_this);
static jim_opt_i64 jim_m_Float_floor(double jl_this);
static jim_opt_i64 jim_m_Float_round(double jl_this);
static jim_opt_i64 jim_m_Float_trunc(double jl_this);
static int64_t jim_m_Float_ceil(double jl_this);
static jim_opt_f64 jim_m_Float_min(double jl_this, double jl_other);
static jim_opt_f64 jim_m_Float_max(double jl_this, double jl_other);
static jim_opt_f64 jim_m_Float_clamp(double jl_this, double jl_low, double jl_high);
static jim_opt_bool jim_m_Float_is_close_to(double jl_this, double jl_other, double jl_epsilon);
static jim_opt_f64 jim_m_Float_fract(double jl_this);
static jim_opt_f64 jim_m_Float_sqrt(double jl_this);
static jim_opt_f64 jim_m_Float_pow(double jl_this, double jl_exp);
static jim_opt_bool jim_m_Float_is_nan(double jl_this);
static jim_opt_bool jim_m_Float_is_infinite(double jl_this);
static jim_opt_bool jim_m_Float_is_finite(double jl_this);
static int64_t jim_m_Integer_plus(int64_t jl_this, int64_t jl_other);
static int64_t jim_m_Integer_minus(int64_t jl_this, int64_t jl_other);
static int64_t jim_m_Integer_times(int64_t jl_this, int64_t jl_other);
static double jim_m_Integer_divide(int64_t jl_this, int64_t jl_other);
static int64_t jim_m_Integer_int_divide(int64_t jl_this, int64_t jl_other);
static int64_t jim_m_Integer_mod(int64_t jl_this, int64_t jl_other);
static int64_t jim_m_Integer_negate(int64_t jl_this);
static bool jim_m_Integer_equals(int64_t jl_this, int64_t jl_other);
static bool jim_m_Integer_less_than(int64_t jl_this, int64_t jl_other);
static double jim_m_Integer_to_float(int64_t jl_this);
static jim_str jim_m_Integer_to_string(int64_t jl_this);
static jim_opt_i64 jim_m_Integer_abs(int64_t jl_this);
static jim_opt_i64 jim_m_Integer_sign(int64_t jl_this);
static jim_opt_i64 jim_m_Integer_pow(int64_t jl_this, int64_t jl_exp);
static jim_opt_i64 jim_m_Integer_min(int64_t jl_this, int64_t jl_other);
static jim_opt_i64 jim_m_Integer_max(int64_t jl_this, int64_t jl_other);
static jim_opt_i64 jim_m_Integer_clamp(int64_t jl_this, int64_t jl_low, int64_t jl_high);
static jim_opt_bool jim_m_Integer_is_even(int64_t jl_this);
static jim_opt_bool jim_m_Integer_is_odd(int64_t jl_this);
static jim_opt_char jim_m_Integer_to_char(int64_t jl_this);
static jim_opt_i64 jim_m_Integer_digit_count(int64_t jl_this);
static jim_opt_i64 jim_m_Integer_bit_and(int64_t jl_this, int64_t jl_other);
static jim_opt_i64 jim_m_Integer_bit_or(int64_t jl_this, int64_t jl_other);
static jim_opt_i64 jim_m_Integer_bit_xor(int64_t jl_this, int64_t jl_other);
static jim_opt_i64 jim_m_Integer_bit_not(int64_t jl_this);
static jim_opt_i64 jim_m_Integer_shift_left(int64_t jl_this, int64_t jl_bits);
static jim_opt_i64 jim_m_Integer_shift_right(int64_t jl_this, int64_t jl_bits);
static jim_str jim_m_String_plus(jim_str jl_this, jim_str jl_other);
static bool jim_m_String_equals(jim_str jl_this, jim_str jl_other);
static bool jim_m_String_less_than(jim_str jl_this, jim_str jl_other);
static int64_t jim_m_String_length(jim_str jl_this);
static jim_str jim_m_String_to_string(jim_str jl_this);
static uint8_t jim_m_String_get(jim_str jl_this, int64_t jl_index);
static bool jim_m_String_contains(jim_str jl_this, uint8_t jl_value);
static jim_str jim_m_String_substr(jim_str jl_this, int64_t jl_start, int64_t jl_end);
static jim_str jim_m_String_capitalize(jim_str jl_this);
static jim_str jim_m_String_upper(jim_str jl_this);
static jim_str jim_m_String_lower(jim_str jl_this);
static int64_t jim_m_String_count(jim_str jl_this, uint8_t jl_value);
static bool jim_m_String_startsWith(jim_str jl_this, jim_str jl_value);
static bool jim_m_String_endsWith(jim_str jl_this, jim_str jl_value);
static int64_t jim_m_String_index(jim_str jl_this, jim_str jl_value);
static bool jim_m_String_isAlnum(jim_str jl_this);
static bool jim_m_String_isAlpha(jim_str jl_this);
static bool jim_m_String_isAscii(jim_str jl_this);
static bool jim_m_String_isDecimal(jim_str jl_this);
static bool jim_m_String_isLower(jim_str jl_this);
static bool jim_m_String_isSpace(jim_str jl_this);
static bool jim_m_String_isUpper(jim_str jl_this);
static jim_c_Array_String_* jim_m_String_split(jim_str jl_this, uint8_t jl_delim);
static jim_opt_str jim_m_String_trim(jim_str jl_this);
static jim_opt_str jim_m_String_ltrim(jim_str jl_this);
static jim_opt_str jim_m_String_rtrim(jim_str jl_this);
static jim_opt_str jim_m_String_replace(jim_str jl_this, jim_str jl_target, jim_str jl_new);
static jim_opt_str jim_m_String_repeat(jim_str jl_this, int64_t jl_n);
static jim_opt_str jim_m_String_reverse(jim_str jl_this);
static jim_opt_i64 jim_m_String_lastIndex(jim_str jl_this, jim_str jl_value);
static jim_c_Array_String_* jim_m_String_lines(jim_str jl_this);
static jim_opt_str jim_m_String_join(jim_str jl_this, jim_c_Array_String_* jl_values);
static jim_opt_str jim_m_String_padLeft(jim_str jl_this, uint8_t jl_c, int64_t jl_n);
static jim_opt_str jim_m_String_padRight(jim_str jl_this, uint8_t jl_c, int64_t jl_n);
static jim_opt_str jim_m_String_removePrefix(jim_str jl_this, jim_str jl_prefix);
static jim_opt_str jim_m_String_removeSuffix(jim_str jl_this, jim_str jl_suffix);
static jim_opt_str jim_m_String_swapCase(jim_str jl_this);
static jim_opt_str jim_m_String_title(jim_str jl_this);
static jim_opt_bool jim_m_String_isTitle(jim_str jl_this);
static jim_opt_bool jim_m_String_equalsIgnoreCase(jim_str jl_this, jim_str jl_other);
static jim_opt_i64 jim_m_String_to_integer(jim_str jl_this);
static jim_opt_f64 jim_m_String_to_float(jim_str jl_this);
static jim_c_Array_Integer_* jim_new_Array_Integer_(int64_t jl_length);
static int64_t jim_m_Array_Integer__get(jim_c_Array_Integer_* jl_this, int64_t jl_index);
static void jim_m_Array_Integer__set(jim_c_Array_Integer_* jl_this, int64_t jl_index, int64_t jl_value);
static int64_t jim_m_Array_Integer__length(jim_c_Array_Integer_* jl_this);
static jim_str jim_m_Array_Integer__to_string(jim_c_Array_Integer_* jl_this);
static void jim_m_Array_Integer__fill(jim_c_Array_Integer_* jl_this, int64_t jl_value);
static void jim_m_Array_Integer__swap(jim_c_Array_Integer_* jl_this, int64_t jl_a, int64_t jl_b);
static jim_c_Array_Integer_* jim_m_Array_Integer__clone(jim_c_Array_Integer_* jl_this);
static jim_c_Array_Integer_* jim_m_Array_Integer__slice(jim_c_Array_Integer_* jl_this, int64_t jl_start, int64_t jl_end);
static jim_c_Array_Integer_* jim_m_Array_Integer__concat(jim_c_Array_Integer_* jl_this, jim_c_Array_Integer_* jl_other);
static jim_opt_bool jim_m_Array_Integer__is_empty(jim_c_Array_Integer_* jl_this);
static jim_opt_bool jim_m_Array_Integer__equals(jim_c_Array_Integer_* jl_this, jim_c_Array_Integer_* jl_other);
static void jim_m_Array_Integer__sort(jim_c_Array_Integer_* jl_this);
static void jim_m_Array_Integer__reverse(jim_c_Array_Integer_* jl_this);
static jim_c_Vector_Integer_* jim_m_Array_Integer__to_vector(jim_c_Array_Integer_* jl_this);
static jim_c_Vector_Integer_* jim_new_Vector_Integer_(void);
static void jim_m_Vector_Integer__push(jim_c_Vector_Integer_* jl_this, int64_t jl_value);
static int64_t jim_m_Vector_Integer__get(jim_c_Vector_Integer_* jl_this, int64_t jl_index);
static void jim_m_Vector_Integer__set(jim_c_Vector_Integer_* jl_this, int64_t jl_index, int64_t jl_value);
static int64_t jim_m_Vector_Integer__length(jim_c_Vector_Integer_* jl_this);
static jim_str jim_m_Vector_Integer__to_string(jim_c_Vector_Integer_* jl_this);
static void jim_m_Vector_Integer__fill(jim_c_Vector_Integer_* jl_this, int64_t jl_value);
static void jim_m_Vector_Integer__swap(jim_c_Vector_Integer_* jl_this, int64_t jl_a, int64_t jl_b);
static jim_c_Vector_Integer_* jim_m_Vector_Integer__clone(jim_c_Vector_Integer_* jl_this);
static jim_c_Vector_Integer_* jim_m_Vector_Integer__slice(jim_c_Vector_Integer_* jl_this, int64_t jl_start, int64_t jl_end);
static jim_c_Vector_Integer_* jim_m_Vector_Integer__concat(jim_c_Vector_Integer_* jl_this, jim_c_Vector_Integer_* jl_other);
static jim_opt_bool jim_m_Vector_Integer__is_empty(jim_c_Vector_Integer_* jl_this);
static jim_opt_bool jim_m_Vector_Integer__equals(jim_c_Vector_Integer_* jl_this, jim_c_Vector_Integer_* jl_other);
static void jim_m_Vector_Integer__sort(jim_c_Vector_Integer_* jl_this);
static void jim_m_Vector_Integer__reverse(jim_c_Vector_Integer_* jl_this);
static jim_c_Array_Integer_* jim_m_Vector_Integer__to_array(jim_c_Vector_Integer_* jl_this);
static jim_opt_i64 jim_m_Vector_Integer__peek(jim_c_Vector_Integer_* jl_this);
static void jim_m_Vector_Integer__insert(jim_c_Vector_Integer_* jl_this, int64_t jl_index, int64_t jl_value);
static jim_opt_i64 jim_m_Vector_Integer__remove(jim_c_Vector_Integer_* jl_this, int64_t jl_index);
static void jim_m_Vector_Integer__remove_value(jim_c_Vector_Integer_* jl_this, int64_t jl_value);
static void jim_m_Vector_Integer__clear(jim_c_Vector_Integer_* jl_this);
static void jim_m_Vector_Integer__extend(jim_c_Vector_Integer_* jl_this, jim_c_Vector_Integer_* jl_other);
static jim_opt_i64 jim_m_Vector_Integer__capacity(jim_c_Vector_Integer_* jl_this);
static void jim_m_Vector_Integer__reserve(jim_c_Vector_Integer_* jl_this, int64_t jl_size);
static jim_c_Vector_String_* jim_new_Vector_String_(void);
static void jim_m_Vector_String__push(jim_c_Vector_String_* jl_this, jim_str jl_value);
static jim_str jim_m_Vector_String__get(jim_c_Vector_String_* jl_this, int64_t jl_index);
static void jim_m_Vector_String__set(jim_c_Vector_String_* jl_this, int64_t jl_index, jim_str jl_value);
static int64_t jim_m_Vector_String__length(jim_c_Vector_String_* jl_this);
static jim_str jim_m_Vector_String__to_string(jim_c_Vector_String_* jl_this);
static void jim_m_Vector_String__fill(jim_c_Vector_String_* jl_this, jim_str jl_value);
static void jim_m_Vector_String__swap(jim_c_Vector_String_* jl_this, int64_t jl_a, int64_t jl_b);
static jim_c_Vector_String_* jim_m_Vector_String__clone(jim_c_Vector_String_* jl_this);
static jim_c_Vector_String_* jim_m_Vector_String__slice(jim_c_Vector_String_* jl_this, int64_t jl_start, int64_t jl_end);
static jim_c_Vector_String_* jim_m_Vector_String__concat(jim_c_Vector_String_* jl_this, jim_c_Vector_String_* jl_other);
static jim_opt_bool jim_m_Vector_String__is_empty(jim_c_Vector_String_* jl_this);
static jim_opt_bool jim_m_Vector_String__equals(jim_c_Vector_String_* jl_this, jim_c_Vector_String_* jl_other);
static void jim_m_Vector_String__sort(jim_c_Vector_String_* jl_this);
static void jim_m_Vector_String__reverse(jim_c_Vector_String_* jl_this);
static jim_c_Array_String_* jim_m_Vector_String__to_array(jim_c_Vector_String_* jl_this);
static jim_opt_str jim_m_Vector_String__peek(jim_c_Vector_String_* jl_this);
static void jim_m_Vector_String__insert(jim_c_Vector_String_* jl_this, int64_t jl_index, jim_str jl_value);
static jim_opt_str jim_m_Vector_String__remove(jim_c_Vector_String_* jl_this, int64_t jl_index);
static void jim_m_Vector_String__remove_value(jim_c_Vector_String_* jl_this, jim_str jl_value);
static void jim_m_Vector_String__clear(jim_c_Vector_String_* jl_this);
static void jim_m_Vector_String__extend(jim_c_Vector_String_* jl_this, jim_c_Vector_String_* jl_other);
static jim_opt_i64 jim_m_Vector_String__capacity(jim_c_Vector_String_* jl_this);
static void jim_m_Vector_String__reserve(jim_c_Vector_String_* jl_this, int64_t jl_size);
static jim_c_Array_String_* jim_new_Array_String_(int64_t jl_length);
static jim_str jim_m_Array_String__get(jim_c_Array_String_* jl_this, int64_t jl_index);
static void jim_m_Array_String__set(jim_c_Array_String_* jl_this, int64_t jl_index, jim_str jl_value);
static int64_t jim_m_Array_String__length(jim_c_Array_String_* jl_this);
static jim_str jim_m_Array_String__to_string(jim_c_Array_String_* jl_this);
static void jim_m_Array_String__fill(jim_c_Array_String_* jl_this, jim_str jl_value);
static void jim_m_Array_String__swap(jim_c_Array_String_* jl_this, int64_t jl_a, int64_t jl_b);
static jim_c_Array_String_* jim_m_Array_String__clone(jim_c_Array_String_* jl_this);
static jim_c_Array_String_* jim_m_Array_String__slice(jim_c_Array_String_* jl_this, int64_t jl_start, int64_t jl_end);
static jim_c_Array_String_* jim_m_Array_String__concat(jim_c_Array_String_* jl_this, jim_c_Array_String_* jl_other);
static jim_opt_bool jim_m_Array_String__is_empty(jim_c_Array_String_* jl_this);
static jim_opt_bool jim_m_Array_String__equals(jim_c_Array_String_* jl_this, jim_c_Array_String_* jl_other);
static void jim_m_Array_String__sort(jim_c_Array_String_* jl_this);
static void jim_m_Array_String__reverse(jim_c_Array_String_* jl_this);
static jim_c_Vector_String_* jim_m_Array_String__to_vector(jim_c_Array_String_* jl_this);
static int64_t jim_user_main(void);
static void jim_user_print(jim_str jl_s);
static jim_opt_str jim_user_input(void);
static void jim_user_print_err(jim_str jl_msg);
static jim_opt_str jim_user_read_file(jim_str jl_file);
static jim_opt_i64 jim_user_write_file(jim_str jl_file, jim_str jl_content);
static jim_opt_i64 jim_user_append_file(jim_str jl_file, jim_str jl_content);
static jim_opt_bool jim_user_file_exists(jim_str jl_file);

static jim_str jim_m_Exception_msg(jim_str jl_this) {
    return rt_exc_msg(jl_this);
}

static bool jim_m_Char_equals(uint8_t jl_this, uint8_t jl_other) {
    return rt_char_eq(jl_this, jl_other);
}

static bool jim_m_Char_less_than(uint8_t jl_this, uint8_t jl_other) {
    return rt_char_lt(jl_this, jl_other);
}

static jim_str jim_m_Char_to_string(uint8_t jl_this) {
    return rt_char_to_string(jl_this);
}

static int64_t jim_m_Char_to_integer(uint8_t jl_this) {
    return rt_char_to_i64(jl_this);
}

static uint8_t jim_m_Char_to_upper(uint8_t jl_this) {
    if ((!(jim_m_Integer_less_than(jim_m_Char_to_integer(jl_this), INT64_C(97))) && !(jim_m_Integer_less_than(INT64_C(122), jim_m_Char_to_integer(jl_this))))) {
        return rt_i64_to_char(jim_m_Integer_minus(rt_char_to_i64(jl_this), INT64_C(32)));
    }
    return jl_this;
}

static uint8_t jim_m_Char_to_lower(uint8_t jl_this) {
    if ((!(jim_m_Integer_less_than(jim_m_Char_to_integer(jl_this), INT64_C(65))) && !(jim_m_Integer_less_than(INT64_C(90), jim_m_Char_to_integer(jl_this))))) {
        return rt_i64_to_char(jim_m_Integer_plus(rt_char_to_i64(jl_this), INT64_C(32)));
    }
    return jl_this;
}

static jim_opt_bool jim_m_Char_is_alpha(uint8_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Char_is_digit(uint8_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Char_is_alnum(uint8_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Char_is_upper(uint8_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Char_is_lower(uint8_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Char_is_space(uint8_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Char_is_punct(uint8_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Char_is_ascii_printable(uint8_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_i64 jim_m_Char_digit_value(uint8_t jl_this) {
    return rt_opt_i64_none();
}

static bool jim_m_Bool_equals(bool jl_this, bool jl_other) {
    return rt_bool_eq(jl_this, jl_other);
}

static jim_str jim_m_Bool_to_string(bool jl_this) {
    if (jl_this) {
        return rt_str_lit("true", 4);
    }
    return rt_str_lit("false", 5);
}

static int64_t jim_m_Bool_to_integer(bool jl_this) {
    if (jl_this) {
        return INT64_C(1);
    }
    return INT64_C(0);
}

static double jim_m_Float_plus(double jl_this, double jl_other) {
    return rt_f64_add(jl_this, jl_other);
}

static double jim_m_Float_minus(double jl_this, double jl_other) {
    return rt_f64_sub(jl_this, jl_other);
}

static double jim_m_Float_times(double jl_this, double jl_other) {
    return rt_f64_mul(jl_this, jl_other);
}

static double jim_m_Float_divide(double jl_this, double jl_other) {
    return rt_f64_div(jl_this, jl_other);
}

static double jim_m_Float_negate(double jl_this) {
    return rt_f64_neg(jl_this);
}

static bool jim_m_Float_equals(double jl_this, double jl_other) {
    return rt_f64_eq(jl_this, jl_other);
}

static bool jim_m_Float_less_than(double jl_this, double jl_other) {
    return rt_f64_lt(jl_this, jl_other);
}

static int64_t jim_m_Float_to_integer(double jl_this) {
    return rt_f64_to_i64(jl_this);
}

static jim_str jim_m_Float_to_string(double jl_this) {
    return rt_f64_to_string(jl_this);
}

static jim_opt_f64 jim_m_Float_abs(double jl_this) {
    return rt_opt_f64_none();
}

static jim_opt_f64 jim_m_Float_sign(double jl_this) {
    return rt_opt_f64_none();
}

static jim_opt_i64 jim_m_Float_floor(double jl_this) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Float_round(double jl_this) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Float_trunc(double jl_this) {
    return rt_opt_i64_none();
}

static int64_t jim_m_Float_ceil(double jl_this) {
    return rt_f64_to_i64(jim_m_Float_plus(jl_this, jim_m_Float_minus(jim_m_Integer_to_float(INT64_C(1)), jim_m_Float_minus(jl_this, jim_m_Integer_to_float(rt_f64_to_i64(jl_this))))));
}

static jim_opt_f64 jim_m_Float_min(double jl_this, double jl_other) {
    return rt_opt_f64_none();
}

static jim_opt_f64 jim_m_Float_max(double jl_this, double jl_other) {
    return rt_opt_f64_none();
}

static jim_opt_f64 jim_m_Float_clamp(double jl_this, double jl_low, double jl_high) {
    return rt_opt_f64_none();
}

static jim_opt_bool jim_m_Float_is_close_to(double jl_this, double jl_other, double jl_epsilon) {
    return rt_opt_bool_none();
}

static jim_opt_f64 jim_m_Float_fract(double jl_this) {
    return rt_opt_f64_none();
}

static jim_opt_f64 jim_m_Float_sqrt(double jl_this) {
    return rt_opt_f64_none();
}

static jim_opt_f64 jim_m_Float_pow(double jl_this, double jl_exp) {
    return rt_opt_f64_none();
}

static jim_opt_bool jim_m_Float_is_nan(double jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Float_is_infinite(double jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Float_is_finite(double jl_this) {
    return rt_opt_bool_none();
}

static int64_t jim_m_Integer_plus(int64_t jl_this, int64_t jl_other) {
    return rt_i64_add(jl_this, jl_other);
}

static int64_t jim_m_Integer_minus(int64_t jl_this, int64_t jl_other) {
    return rt_i64_sub(jl_this, jl_other);
}

static int64_t jim_m_Integer_times(int64_t jl_this, int64_t jl_other) {
    return rt_i64_mul(jl_this, jl_other);
}

static double jim_m_Integer_divide(int64_t jl_this, int64_t jl_other) {
    return rt_f64_div(rt_i64_to_f64(jl_this), rt_i64_to_f64(jl_other));
}

static int64_t jim_m_Integer_int_divide(int64_t jl_this, int64_t jl_other) {
    return rt_i64_divtrunc(jl_this, jl_other);
}

static int64_t jim_m_Integer_mod(int64_t jl_this, int64_t jl_other) {
    return rt_i64_mod(jl_this, jl_other);
}

static int64_t jim_m_Integer_negate(int64_t jl_this) {
    return rt_i64_neg(jl_this);
}

static bool jim_m_Integer_equals(int64_t jl_this, int64_t jl_other) {
    return rt_i64_eq(jl_this, jl_other);
}

static bool jim_m_Integer_less_than(int64_t jl_this, int64_t jl_other) {
    return rt_i64_lt(jl_this, jl_other);
}

static double jim_m_Integer_to_float(int64_t jl_this) {
    return rt_i64_to_f64(jl_this);
}

static jim_str jim_m_Integer_to_string(int64_t jl_this) {
    return rt_i64_to_string(jl_this);
}

static jim_opt_i64 jim_m_Integer_abs(int64_t jl_this) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_sign(int64_t jl_this) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_pow(int64_t jl_this, int64_t jl_exp) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_min(int64_t jl_this, int64_t jl_other) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_max(int64_t jl_this, int64_t jl_other) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_clamp(int64_t jl_this, int64_t jl_low, int64_t jl_high) {
    return rt_opt_i64_none();
}

static jim_opt_bool jim_m_Integer_is_even(int64_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Integer_is_odd(int64_t jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_char jim_m_Integer_to_char(int64_t jl_this) {
    return rt_opt_char_none();
}

static jim_opt_i64 jim_m_Integer_digit_count(int64_t jl_this) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_bit_and(int64_t jl_this, int64_t jl_other) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_bit_or(int64_t jl_this, int64_t jl_other) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_bit_xor(int64_t jl_this, int64_t jl_other) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_bit_not(int64_t jl_this) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_shift_left(int64_t jl_this, int64_t jl_bits) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_m_Integer_shift_right(int64_t jl_this, int64_t jl_bits) {
    return rt_opt_i64_none();
}

static jim_str jim_m_String_plus(jim_str jl_this, jim_str jl_other) {
    return rt_str_concat(jl_this, jl_other);
}

static bool jim_m_String_equals(jim_str jl_this, jim_str jl_other) {
    return rt_str_eq(jl_this, jl_other);
}

static bool jim_m_String_less_than(jim_str jl_this, jim_str jl_other) {
    return rt_str_lt(jl_this, jl_other);
}

static int64_t jim_m_String_length(jim_str jl_this) {
    return rt_str_len(jl_this);
}

static jim_str jim_m_String_to_string(jim_str jl_this) {
    return jl_this;
}

static uint8_t jim_m_String_get(jim_str jl_this, int64_t jl_index) {
    if ((jim_m_Integer_less_than(jl_index, INT64_C(0)) || !(jim_m_Integer_less_than(jl_index, jim_m_String_length(jl_this))))) {
        rt_panic_at(rt_str_lit("String index out of range.", 26), "std/core/string.j", 23, "String.get");
    }
    return rt_str_byte(jl_this, jl_index);
}

static bool jim_m_String_contains(jim_str jl_this, uint8_t jl_value) {
    {
        jim_str jl___jim_it_30_9 = jl_this;
        for (int64_t jl___jim_i_30_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_30_9, jim_m_String_length(jl___jim_it_30_9)); jl___jim_i_30_9 = jim_m_Integer_plus(jl___jim_i_30_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_30_9, jl___jim_i_30_9);
            if (jim_m_Char_equals(jl_c, jl_value)) {
                return true;
            }
        }
    }
    return false;
}

static jim_str jim_m_String_substr(jim_str jl_this, int64_t jl_start, int64_t jl_end) {
    jim_str jl_result = rt_str_lit("", 0);
    for (int64_t jl_i = jl_start; !(jim_m_Integer_less_than(jl_end, jl_i)); jl_i = jim_m_Integer_plus(jl_i, INT64_C(1))) {
        jl_result = jim_m_String_plus(jl_result, jim_m_Char_to_string(jim_m_String_get(jl_this, jl_i)));
    }
    return jl_result;
}

static jim_str jim_m_String_capitalize(jim_str jl_this) {
    return jim_m_String_plus(jim_m_Char_to_string(jim_m_Char_to_upper(jim_m_String_get(jl_this, INT64_C(0)))), jim_m_String_substr(jl_this, INT64_C(1), jim_m_Integer_minus(jim_m_String_length(jl_this), INT64_C(1))));
}

static jim_str jim_m_String_upper(jim_str jl_this) {
    jim_str jl_result = rt_str_lit("", 0);
    {
        jim_str jl___jim_it_55_9 = jl_this;
        for (int64_t jl___jim_i_55_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_55_9, jim_m_String_length(jl___jim_it_55_9)); jl___jim_i_55_9 = jim_m_Integer_plus(jl___jim_i_55_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_55_9, jl___jim_i_55_9);
            jl_result = jim_m_String_plus(jl_result, jim_m_Char_to_string(jim_m_Char_to_upper(jl_c)));
        }
    }
    return jl_result;
}

static jim_str jim_m_String_lower(jim_str jl_this) {
    jim_str jl_result = rt_str_lit("", 0);
    {
        jim_str jl___jim_it_64_9 = jl_this;
        for (int64_t jl___jim_i_64_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_64_9, jim_m_String_length(jl___jim_it_64_9)); jl___jim_i_64_9 = jim_m_Integer_plus(jl___jim_i_64_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_64_9, jl___jim_i_64_9);
            jl_result = jim_m_String_plus(jl_result, jim_m_Char_to_string(jim_m_Char_to_lower(jl_c)));
        }
    }
    return jl_result;
}

static int64_t jim_m_String_count(jim_str jl_this, uint8_t jl_value) {
    int64_t jl_result = INT64_C(0);
    {
        jim_str jl___jim_it_73_9 = jl_this;
        for (int64_t jl___jim_i_73_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_73_9, jim_m_String_length(jl___jim_it_73_9)); jl___jim_i_73_9 = jim_m_Integer_plus(jl___jim_i_73_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_73_9, jl___jim_i_73_9);
            if (jim_m_Char_equals(jl_c, jl_value)) {
                jl_result = jim_m_Integer_plus(jl_result, INT64_C(1));
            }
        }
    }
    return jl_result;
}

static bool jim_m_String_startsWith(jim_str jl_this, jim_str jl_value) {
    return jim_m_String_equals(jim_m_String_substr(jl_this, INT64_C(0), jim_m_Integer_minus(jim_m_String_length(jl_value), INT64_C(1))), jl_value);
}

static bool jim_m_String_endsWith(jim_str jl_this, jim_str jl_value) {
    return jim_m_String_equals(jim_m_String_substr(jl_this, jim_m_Integer_minus(jim_m_String_length(jl_this), jim_m_String_length(jl_value)), jim_m_Integer_minus(jim_m_String_length(jl_this), INT64_C(1))), jl_value);
}

static int64_t jim_m_String_index(jim_str jl_this, jim_str jl_value) {
    if (jim_m_Integer_less_than(jim_m_String_length(jl_this), jim_m_String_length(jl_value))) {
        return INT64_C(-1);
    }
    for (int64_t jl_i = INT64_C(0); !(jim_m_Integer_less_than(jim_m_Integer_minus(jim_m_String_length(jl_this), jim_m_String_length(jl_value)), jl_i)); jl_i = jim_m_Integer_plus(jl_i, INT64_C(1))) {
        if (jim_m_String_equals(jim_m_String_substr(jl_this, jl_i, jim_m_Integer_minus(jim_m_Integer_plus(jl_i, jim_m_String_length(jl_value)), INT64_C(1))), jl_value)) {
            return jl_i;
        }
    }
    return INT64_C(-1);
}

static bool jim_m_String_isAlnum(jim_str jl_this) {
    {
        jim_str jl___jim_it_104_9 = jl_this;
        for (int64_t jl___jim_i_104_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_104_9, jim_m_String_length(jl___jim_it_104_9)); jl___jim_i_104_9 = jim_m_Integer_plus(jl___jim_i_104_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_104_9, jl___jim_i_104_9);
            jim_str jl_v = jim_m_Char_to_string(jl_c);
            if ((!(jim_m_String_isAlpha(jl_v)) && !(jim_m_String_isDecimal(jl_v)))) {
                return false;
            }
        }
    }
    return true;
}

static bool jim_m_String_isAlpha(jim_str jl_this) {
    {
        jim_str jl___jim_it_115_9 = jl_this;
        for (int64_t jl___jim_i_115_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_115_9, jim_m_String_length(jl___jim_it_115_9)); jl___jim_i_115_9 = jim_m_Integer_plus(jl___jim_i_115_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_115_9, jl___jim_i_115_9);
            int64_t jl_v = rt_char_to_i64(jl_c);
            if ((!((!(jim_m_Integer_less_than(jl_v, INT64_C(65))) && !(jim_m_Integer_less_than(INT64_C(90), jl_v)))) && !((!(jim_m_Integer_less_than(jl_v, INT64_C(97))) && !(jim_m_Integer_less_than(INT64_C(122), jl_v)))))) {
                return false;
            }
        }
    }
    return true;
}

static bool jim_m_String_isAscii(jim_str jl_this) {
    {
        jim_str jl___jim_it_126_9 = jl_this;
        for (int64_t jl___jim_i_126_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_126_9, jim_m_String_length(jl___jim_it_126_9)); jl___jim_i_126_9 = jim_m_Integer_plus(jl___jim_i_126_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_126_9, jl___jim_i_126_9);
            int64_t jl_v = rt_char_to_i64(jl_c);
            if (!((!(jim_m_Integer_less_than(jl_v, INT64_C(32))) && !(jim_m_Integer_less_than(INT64_C(127), jl_v))))) {
                return false;
            }
        }
    }
    return true;
}

static bool jim_m_String_isDecimal(jim_str jl_this) {
    {
        jim_str jl___jim_it_137_9 = jl_this;
        for (int64_t jl___jim_i_137_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_137_9, jim_m_String_length(jl___jim_it_137_9)); jl___jim_i_137_9 = jim_m_Integer_plus(jl___jim_i_137_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_137_9, jl___jim_i_137_9);
            int64_t jl_v = rt_char_to_i64(jl_c);
            if (!((!(jim_m_Integer_less_than(jl_v, INT64_C(48))) && !(jim_m_Integer_less_than(INT64_C(57), jl_v))))) {
                return false;
            }
        }
    }
    return true;
}

static bool jim_m_String_isLower(jim_str jl_this) {
    {
        jim_str jl___jim_it_148_9 = jl_this;
        for (int64_t jl___jim_i_148_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_148_9, jim_m_String_length(jl___jim_it_148_9)); jl___jim_i_148_9 = jim_m_Integer_plus(jl___jim_i_148_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_148_9, jl___jim_i_148_9);
            if (!(jim_m_Char_equals(jl_c, jim_m_Char_to_lower(jl_c)))) {
                return false;
            }
        }
    }
    return true;
}

static bool jim_m_String_isSpace(jim_str jl_this) {
    {
        jim_str jl___jim_it_158_9 = jl_this;
        for (int64_t jl___jim_i_158_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_158_9, jim_m_String_length(jl___jim_it_158_9)); jl___jim_i_158_9 = jim_m_Integer_plus(jl___jim_i_158_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_158_9, jl___jim_i_158_9);
            if (!(jim_m_Char_equals(jl_c, 32u))) {
                return false;
            }
        }
    }
    return true;
}

static bool jim_m_String_isUpper(jim_str jl_this) {
    {
        jim_str jl___jim_it_168_9 = jl_this;
        for (int64_t jl___jim_i_168_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_168_9, jim_m_String_length(jl___jim_it_168_9)); jl___jim_i_168_9 = jim_m_Integer_plus(jl___jim_i_168_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_168_9, jl___jim_i_168_9);
            if (!(jim_m_Char_equals(jl_c, jim_m_Char_to_upper(jl_c)))) {
                return false;
            }
        }
    }
    return true;
}

static jim_c_Array_String_* jim_m_String_split(jim_str jl_this, uint8_t jl_delim) {
    if (jim_m_String_equals(jl_this, rt_str_lit("", 0))) {
        return ({ jim_c_Array_String_* jim_lit = jim_new_Array_String_(INT64_C(0)); jim_lit; });
    }
    int64_t jl_result_size = jim_m_String_count(jl_this, jl_delim);
    if ((jim_m_Integer_less_than(INT64_C(0), jim_m_String_length(jl_this)) && !(jim_m_Char_equals(jim_m_String_get(jl_this, jim_m_Integer_minus(jim_m_String_length(jl_this), INT64_C(1))), jl_delim)))) {
        jl_result_size = jim_m_Integer_plus(jl_result_size, INT64_C(1));
    }
    jim_c_Array_String_* jl_result = jim_new_Array_String_(jl_result_size);
    jim_str jl_temp = rt_str_lit("", 0);
    int64_t jl_index = INT64_C(0);
    {
        jim_str jl___jim_it_196_9 = jl_this;
        for (int64_t jl___jim_i_196_9 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_196_9, jim_m_String_length(jl___jim_it_196_9)); jl___jim_i_196_9 = jim_m_Integer_plus(jl___jim_i_196_9, INT64_C(1))) {
            uint8_t jl_c = jim_m_String_get(jl___jim_it_196_9, jl___jim_i_196_9);
            if (jim_m_Char_equals(jl_c, jl_delim)) {
                jim_m_Array_String__set(jl_result, jl_index, jl_temp);
                jl_index = jim_m_Integer_plus(jl_index, INT64_C(1));
                jl_temp = rt_str_lit("", 0);
            } else {
                jl_temp = jim_m_String_plus(jl_temp, jim_m_Char_to_string(jl_c));
            }
        }
    }
    if (!(jim_m_String_equals(jl_temp, rt_str_lit("", 0)))) {
        jim_m_Array_String__set(jl_result, jl_index, jl_temp);
    }
    return jl_result;
}

static jim_opt_str jim_m_String_trim(jim_str jl_this) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_ltrim(jim_str jl_this) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_rtrim(jim_str jl_this) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_replace(jim_str jl_this, jim_str jl_target, jim_str jl_new) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_repeat(jim_str jl_this, int64_t jl_n) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_reverse(jim_str jl_this) {
    return rt_opt_str_none();
}

static jim_opt_i64 jim_m_String_lastIndex(jim_str jl_this, jim_str jl_value) {
    return rt_opt_i64_none();
}

static jim_c_Array_String_* jim_m_String_lines(jim_str jl_this) {
    return (jim_c_Array_String_*)NULL;
}

static jim_opt_str jim_m_String_join(jim_str jl_this, jim_c_Array_String_* jl_values) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_padLeft(jim_str jl_this, uint8_t jl_c, int64_t jl_n) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_padRight(jim_str jl_this, uint8_t jl_c, int64_t jl_n) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_removePrefix(jim_str jl_this, jim_str jl_prefix) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_removeSuffix(jim_str jl_this, jim_str jl_suffix) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_swapCase(jim_str jl_this) {
    return rt_opt_str_none();
}

static jim_opt_str jim_m_String_title(jim_str jl_this) {
    return rt_opt_str_none();
}

static jim_opt_bool jim_m_String_isTitle(jim_str jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_String_equalsIgnoreCase(jim_str jl_this, jim_str jl_other) {
    return rt_opt_bool_none();
}

static jim_opt_i64 jim_m_String_to_integer(jim_str jl_this) {
    return rt_opt_i64_none();
}

static jim_opt_f64 jim_m_String_to_float(jim_str jl_this) {
    return rt_opt_f64_none();
}

static jim_c_Array_Integer_* jim_new_Array_Integer_(int64_t jl_length) {
    jim_c_Array_Integer_* jl_this = (jim_c_Array_Integer_*)rt_arena_alloc(sizeof(jim_c_Array_Integer_));
    jl_this->f_buffer = jim_buf_Integer_alloc(INT64_C(0));
    jl_this->f_size = INT64_C(0);
    if (jim_m_Integer_less_than(jl_length, INT64_C(0))) {
        rt_panic_at(rt_str_lit("Array length cannot be negative.", 32), "std/core/array.j", 10, "Array<Integer> constructor");
    }
    (jl_this)->f_buffer = jim_buf_Integer_alloc(jl_length);
    (jl_this)->f_size = jl_length;
    return jl_this;
}

static int64_t jim_m_Array_Integer__get(jim_c_Array_Integer_* jl_this, int64_t jl_index) {
    if ((jim_m_Integer_less_than(jl_index, INT64_C(0)) || !(jim_m_Integer_less_than(jl_index, (jl_this)->f_size)))) {
        rt_panic_at(rt_str_lit("Array index out of bounds", 25), "std/core/array.j", 20, "Array<Integer>.get");
    }
    return jim_buf_Integer_get((jl_this)->f_buffer, jl_index);
}

static void jim_m_Array_Integer__set(jim_c_Array_Integer_* jl_this, int64_t jl_index, int64_t jl_value) {
    if ((jim_m_Integer_less_than(jl_index, INT64_C(0)) || !(jim_m_Integer_less_than(jl_index, (jl_this)->f_size)))) {
        rt_panic_at(rt_str_lit("Array index out of bounds", 25), "std/core/array.j", 29, "Array<Integer>.set");
    }
    jim_buf_Integer_set((jl_this)->f_buffer, jl_index, jl_value);
}

static int64_t jim_m_Array_Integer__length(jim_c_Array_Integer_* jl_this) {
    return (jl_this)->f_size;
}

static jim_str jim_m_Array_Integer__to_string(jim_c_Array_Integer_* jl_this) {
    jim_str jl_result = rt_str_lit("[", 1);
    for (int64_t jl_i = INT64_C(0); jim_m_Integer_less_than(jl_i, (jl_this)->f_size); jl_i = jim_m_Integer_plus(jl_i, INT64_C(1))) {
        if (jim_m_Integer_equals(jl_i, jim_m_Integer_minus((jl_this)->f_size, INT64_C(1)))) {
            jl_result = jim_m_String_plus(jl_result, jim_m_Integer_to_string(jim_buf_Integer_get((jl_this)->f_buffer, jl_i)));
        } else {
            jl_result = jim_m_String_plus(jl_result, jim_m_String_plus(jim_m_Integer_to_string(jim_buf_Integer_get((jl_this)->f_buffer, jl_i)), rt_str_lit(", ", 2)));
        }
    }
    jl_result = jim_m_String_plus(jl_result, rt_str_lit("]", 1));
    return jl_result;
}

static void jim_m_Array_Integer__fill(jim_c_Array_Integer_* jl_this, int64_t jl_value) {
}

static void jim_m_Array_Integer__swap(jim_c_Array_Integer_* jl_this, int64_t jl_a, int64_t jl_b) {
}

static jim_c_Array_Integer_* jim_m_Array_Integer__clone(jim_c_Array_Integer_* jl_this) {
    return (jim_c_Array_Integer_*)NULL;
}

static jim_c_Array_Integer_* jim_m_Array_Integer__slice(jim_c_Array_Integer_* jl_this, int64_t jl_start, int64_t jl_end) {
    return (jim_c_Array_Integer_*)NULL;
}

static jim_c_Array_Integer_* jim_m_Array_Integer__concat(jim_c_Array_Integer_* jl_this, jim_c_Array_Integer_* jl_other) {
    return (jim_c_Array_Integer_*)NULL;
}

static jim_opt_bool jim_m_Array_Integer__is_empty(jim_c_Array_Integer_* jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Array_Integer__equals(jim_c_Array_Integer_* jl_this, jim_c_Array_Integer_* jl_other) {
    return rt_opt_bool_none();
}

static void jim_m_Array_Integer__sort(jim_c_Array_Integer_* jl_this) {
}

static void jim_m_Array_Integer__reverse(jim_c_Array_Integer_* jl_this) {
}

static jim_c_Vector_Integer_* jim_m_Array_Integer__to_vector(jim_c_Array_Integer_* jl_this) {
    return (jim_c_Vector_Integer_*)NULL;
}

static jim_c_Vector_Integer_* jim_new_Vector_Integer_(void) {
    jim_c_Vector_Integer_* jl_this = (jim_c_Vector_Integer_*)rt_arena_alloc(sizeof(jim_c_Vector_Integer_));
    jl_this->f_buffer = jim_buf_Integer_alloc(INT64_C(0));
    jl_this->f_idx = INT64_C(0);
    return jl_this;
}

static void jim_m_Vector_Integer__push(jim_c_Vector_Integer_* jl_this, int64_t jl_value) {
    if (jim_m_Integer_equals((jl_this)->f_idx, INT64_C(0))) {
        (jl_this)->f_idx = jim_m_Integer_plus((jl_this)->f_idx, INT64_C(1));
        (jl_this)->f_buffer = jim_buf_Integer_alloc((jl_this)->f_idx);
        jim_buf_Integer_set((jl_this)->f_buffer, INT64_C(0), jl_value);
        return;
    }
    if (jim_m_Integer_equals((jl_this)->f_idx, jim_buf_Integer_capacity((jl_this)->f_buffer))) {
        jim_buf_Integer jl_tmp = jim_buf_Integer_alloc(jim_m_Integer_times(jim_buf_Integer_capacity((jl_this)->f_buffer), INT64_C(2)));
        int64_t jl_i = INT64_C(0);
        while (jim_m_Integer_less_than(jl_i, (jl_this)->f_idx)) {
            jim_buf_Integer_set(jl_tmp, jl_i, jim_buf_Integer_get((jl_this)->f_buffer, jl_i));
            jl_i = jim_m_Integer_plus(jl_i, INT64_C(1));
        }
        jim_buf_Integer_set(jl_tmp, jl_i, jl_value);
        (jl_this)->f_idx = jim_m_Integer_plus(jl_i, INT64_C(1));
        (jl_this)->f_buffer = jl_tmp;
        return;
    }
    jim_buf_Integer_set((jl_this)->f_buffer, (jl_this)->f_idx, jl_value);
    (jl_this)->f_idx = jim_m_Integer_plus((jl_this)->f_idx, INT64_C(1));
}

static int64_t jim_m_Vector_Integer__get(jim_c_Vector_Integer_* jl_this, int64_t jl_index) {
    if ((jim_m_Integer_less_than(jl_index, INT64_C(0)) || !(jim_m_Integer_less_than(jl_index, (jl_this)->f_idx)))) {
        rt_panic_at(rt_str_lit("Vector index out of bounds.", 27), "std/core/vector.j", 44, "Vector<Integer>.get");
    }
    return jim_buf_Integer_get((jl_this)->f_buffer, jl_index);
}

static void jim_m_Vector_Integer__set(jim_c_Vector_Integer_* jl_this, int64_t jl_index, int64_t jl_value) {
    if ((jim_m_Integer_less_than(jl_index, INT64_C(0)) || !(jim_m_Integer_less_than(jl_index, (jl_this)->f_idx)))) {
        rt_panic_at(rt_str_lit("Vector index out of bounds.", 27), "std/core/vector.j", 53, "Vector<Integer>.set");
    }
    jim_buf_Integer_set((jl_this)->f_buffer, jl_index, jl_value);
}

static int64_t jim_m_Vector_Integer__length(jim_c_Vector_Integer_* jl_this) {
    return (jl_this)->f_idx;
}

static jim_str jim_m_Vector_Integer__to_string(jim_c_Vector_Integer_* jl_this) {
    jim_str jl_result = rt_str_lit("[", 1);
    for (int64_t jl_i = INT64_C(0); jim_m_Integer_less_than(jl_i, (jl_this)->f_idx); jl_i = jim_m_Integer_plus(jl_i, INT64_C(1))) {
        if (jim_m_Integer_equals(jl_i, jim_m_Integer_minus((jl_this)->f_idx, INT64_C(1)))) {
            jl_result = jim_m_String_plus(jl_result, jim_m_Integer_to_string(jim_buf_Integer_get((jl_this)->f_buffer, jl_i)));
        } else {
            jl_result = jim_m_String_plus(jl_result, jim_m_String_plus(jim_m_Integer_to_string(jim_buf_Integer_get((jl_this)->f_buffer, jl_i)), rt_str_lit(", ", 2)));
        }
    }
    jl_result = jim_m_String_plus(jl_result, rt_str_lit("]", 1));
    return jl_result;
}

static void jim_m_Vector_Integer__fill(jim_c_Vector_Integer_* jl_this, int64_t jl_value) {
}

static void jim_m_Vector_Integer__swap(jim_c_Vector_Integer_* jl_this, int64_t jl_a, int64_t jl_b) {
}

static jim_c_Vector_Integer_* jim_m_Vector_Integer__clone(jim_c_Vector_Integer_* jl_this) {
    return (jim_c_Vector_Integer_*)NULL;
}

static jim_c_Vector_Integer_* jim_m_Vector_Integer__slice(jim_c_Vector_Integer_* jl_this, int64_t jl_start, int64_t jl_end) {
    return (jim_c_Vector_Integer_*)NULL;
}

static jim_c_Vector_Integer_* jim_m_Vector_Integer__concat(jim_c_Vector_Integer_* jl_this, jim_c_Vector_Integer_* jl_other) {
    return (jim_c_Vector_Integer_*)NULL;
}

static jim_opt_bool jim_m_Vector_Integer__is_empty(jim_c_Vector_Integer_* jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Vector_Integer__equals(jim_c_Vector_Integer_* jl_this, jim_c_Vector_Integer_* jl_other) {
    return rt_opt_bool_none();
}

static void jim_m_Vector_Integer__sort(jim_c_Vector_Integer_* jl_this) {
}

static void jim_m_Vector_Integer__reverse(jim_c_Vector_Integer_* jl_this) {
}

static jim_c_Array_Integer_* jim_m_Vector_Integer__to_array(jim_c_Vector_Integer_* jl_this) {
    return (jim_c_Array_Integer_*)NULL;
}

static jim_opt_i64 jim_m_Vector_Integer__peek(jim_c_Vector_Integer_* jl_this) {
    return rt_opt_i64_none();
}

static void jim_m_Vector_Integer__insert(jim_c_Vector_Integer_* jl_this, int64_t jl_index, int64_t jl_value) {
}

static jim_opt_i64 jim_m_Vector_Integer__remove(jim_c_Vector_Integer_* jl_this, int64_t jl_index) {
    return rt_opt_i64_none();
}

static void jim_m_Vector_Integer__remove_value(jim_c_Vector_Integer_* jl_this, int64_t jl_value) {
}

static void jim_m_Vector_Integer__clear(jim_c_Vector_Integer_* jl_this) {
}

static void jim_m_Vector_Integer__extend(jim_c_Vector_Integer_* jl_this, jim_c_Vector_Integer_* jl_other) {
}

static jim_opt_i64 jim_m_Vector_Integer__capacity(jim_c_Vector_Integer_* jl_this) {
    return rt_opt_i64_none();
}

static void jim_m_Vector_Integer__reserve(jim_c_Vector_Integer_* jl_this, int64_t jl_size) {
}

static jim_c_Vector_String_* jim_new_Vector_String_(void) {
    jim_c_Vector_String_* jl_this = (jim_c_Vector_String_*)rt_arena_alloc(sizeof(jim_c_Vector_String_));
    jl_this->f_buffer = jim_buf_String_alloc(INT64_C(0));
    jl_this->f_idx = INT64_C(0);
    return jl_this;
}

static void jim_m_Vector_String__push(jim_c_Vector_String_* jl_this, jim_str jl_value) {
    if (jim_m_Integer_equals((jl_this)->f_idx, INT64_C(0))) {
        (jl_this)->f_idx = jim_m_Integer_plus((jl_this)->f_idx, INT64_C(1));
        (jl_this)->f_buffer = jim_buf_String_alloc((jl_this)->f_idx);
        jim_buf_String_set((jl_this)->f_buffer, INT64_C(0), jl_value);
        return;
    }
    if (jim_m_Integer_equals((jl_this)->f_idx, jim_buf_String_capacity((jl_this)->f_buffer))) {
        jim_buf_String jl_tmp = jim_buf_String_alloc(jim_m_Integer_times(jim_buf_String_capacity((jl_this)->f_buffer), INT64_C(2)));
        int64_t jl_i = INT64_C(0);
        while (jim_m_Integer_less_than(jl_i, (jl_this)->f_idx)) {
            jim_buf_String_set(jl_tmp, jl_i, jim_buf_String_get((jl_this)->f_buffer, jl_i));
            jl_i = jim_m_Integer_plus(jl_i, INT64_C(1));
        }
        jim_buf_String_set(jl_tmp, jl_i, jl_value);
        (jl_this)->f_idx = jim_m_Integer_plus(jl_i, INT64_C(1));
        (jl_this)->f_buffer = jl_tmp;
        return;
    }
    jim_buf_String_set((jl_this)->f_buffer, (jl_this)->f_idx, jl_value);
    (jl_this)->f_idx = jim_m_Integer_plus((jl_this)->f_idx, INT64_C(1));
}

static jim_str jim_m_Vector_String__get(jim_c_Vector_String_* jl_this, int64_t jl_index) {
    if ((jim_m_Integer_less_than(jl_index, INT64_C(0)) || !(jim_m_Integer_less_than(jl_index, (jl_this)->f_idx)))) {
        rt_panic_at(rt_str_lit("Vector index out of bounds.", 27), "std/core/vector.j", 44, "Vector<String>.get");
    }
    return jim_buf_String_get((jl_this)->f_buffer, jl_index);
}

static void jim_m_Vector_String__set(jim_c_Vector_String_* jl_this, int64_t jl_index, jim_str jl_value) {
    if ((jim_m_Integer_less_than(jl_index, INT64_C(0)) || !(jim_m_Integer_less_than(jl_index, (jl_this)->f_idx)))) {
        rt_panic_at(rt_str_lit("Vector index out of bounds.", 27), "std/core/vector.j", 53, "Vector<String>.set");
    }
    jim_buf_String_set((jl_this)->f_buffer, jl_index, jl_value);
}

static int64_t jim_m_Vector_String__length(jim_c_Vector_String_* jl_this) {
    return (jl_this)->f_idx;
}

static jim_str jim_m_Vector_String__to_string(jim_c_Vector_String_* jl_this) {
    jim_str jl_result = rt_str_lit("[", 1);
    for (int64_t jl_i = INT64_C(0); jim_m_Integer_less_than(jl_i, (jl_this)->f_idx); jl_i = jim_m_Integer_plus(jl_i, INT64_C(1))) {
        if (jim_m_Integer_equals(jl_i, jim_m_Integer_minus((jl_this)->f_idx, INT64_C(1)))) {
            jl_result = jim_m_String_plus(jl_result, jim_m_String_to_string(jim_buf_String_get((jl_this)->f_buffer, jl_i)));
        } else {
            jl_result = jim_m_String_plus(jl_result, jim_m_String_plus(jim_m_String_to_string(jim_buf_String_get((jl_this)->f_buffer, jl_i)), rt_str_lit(", ", 2)));
        }
    }
    jl_result = jim_m_String_plus(jl_result, rt_str_lit("]", 1));
    return jl_result;
}

static void jim_m_Vector_String__fill(jim_c_Vector_String_* jl_this, jim_str jl_value) {
}

static void jim_m_Vector_String__swap(jim_c_Vector_String_* jl_this, int64_t jl_a, int64_t jl_b) {
}

static jim_c_Vector_String_* jim_m_Vector_String__clone(jim_c_Vector_String_* jl_this) {
    return (jim_c_Vector_String_*)NULL;
}

static jim_c_Vector_String_* jim_m_Vector_String__slice(jim_c_Vector_String_* jl_this, int64_t jl_start, int64_t jl_end) {
    return (jim_c_Vector_String_*)NULL;
}

static jim_c_Vector_String_* jim_m_Vector_String__concat(jim_c_Vector_String_* jl_this, jim_c_Vector_String_* jl_other) {
    return (jim_c_Vector_String_*)NULL;
}

static jim_opt_bool jim_m_Vector_String__is_empty(jim_c_Vector_String_* jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Vector_String__equals(jim_c_Vector_String_* jl_this, jim_c_Vector_String_* jl_other) {
    return rt_opt_bool_none();
}

static void jim_m_Vector_String__sort(jim_c_Vector_String_* jl_this) {
}

static void jim_m_Vector_String__reverse(jim_c_Vector_String_* jl_this) {
}

static jim_c_Array_String_* jim_m_Vector_String__to_array(jim_c_Vector_String_* jl_this) {
    return (jim_c_Array_String_*)NULL;
}

static jim_opt_str jim_m_Vector_String__peek(jim_c_Vector_String_* jl_this) {
    return rt_opt_str_none();
}

static void jim_m_Vector_String__insert(jim_c_Vector_String_* jl_this, int64_t jl_index, jim_str jl_value) {
}

static jim_opt_str jim_m_Vector_String__remove(jim_c_Vector_String_* jl_this, int64_t jl_index) {
    return rt_opt_str_none();
}

static void jim_m_Vector_String__remove_value(jim_c_Vector_String_* jl_this, jim_str jl_value) {
}

static void jim_m_Vector_String__clear(jim_c_Vector_String_* jl_this) {
}

static void jim_m_Vector_String__extend(jim_c_Vector_String_* jl_this, jim_c_Vector_String_* jl_other) {
}

static jim_opt_i64 jim_m_Vector_String__capacity(jim_c_Vector_String_* jl_this) {
    return rt_opt_i64_none();
}

static void jim_m_Vector_String__reserve(jim_c_Vector_String_* jl_this, int64_t jl_size) {
}

static jim_c_Array_String_* jim_new_Array_String_(int64_t jl_length) {
    jim_c_Array_String_* jl_this = (jim_c_Array_String_*)rt_arena_alloc(sizeof(jim_c_Array_String_));
    jl_this->f_buffer = jim_buf_String_alloc(INT64_C(0));
    jl_this->f_size = INT64_C(0);
    if (jim_m_Integer_less_than(jl_length, INT64_C(0))) {
        rt_panic_at(rt_str_lit("Array length cannot be negative.", 32), "std/core/array.j", 10, "Array<String> constructor");
    }
    (jl_this)->f_buffer = jim_buf_String_alloc(jl_length);
    (jl_this)->f_size = jl_length;
    return jl_this;
}

static jim_str jim_m_Array_String__get(jim_c_Array_String_* jl_this, int64_t jl_index) {
    if ((jim_m_Integer_less_than(jl_index, INT64_C(0)) || !(jim_m_Integer_less_than(jl_index, (jl_this)->f_size)))) {
        rt_panic_at(rt_str_lit("Array index out of bounds", 25), "std/core/array.j", 20, "Array<String>.get");
    }
    return jim_buf_String_get((jl_this)->f_buffer, jl_index);
}

static void jim_m_Array_String__set(jim_c_Array_String_* jl_this, int64_t jl_index, jim_str jl_value) {
    if ((jim_m_Integer_less_than(jl_index, INT64_C(0)) || !(jim_m_Integer_less_than(jl_index, (jl_this)->f_size)))) {
        rt_panic_at(rt_str_lit("Array index out of bounds", 25), "std/core/array.j", 29, "Array<String>.set");
    }
    jim_buf_String_set((jl_this)->f_buffer, jl_index, jl_value);
}

static int64_t jim_m_Array_String__length(jim_c_Array_String_* jl_this) {
    return (jl_this)->f_size;
}

static jim_str jim_m_Array_String__to_string(jim_c_Array_String_* jl_this) {
    jim_str jl_result = rt_str_lit("[", 1);
    for (int64_t jl_i = INT64_C(0); jim_m_Integer_less_than(jl_i, (jl_this)->f_size); jl_i = jim_m_Integer_plus(jl_i, INT64_C(1))) {
        if (jim_m_Integer_equals(jl_i, jim_m_Integer_minus((jl_this)->f_size, INT64_C(1)))) {
            jl_result = jim_m_String_plus(jl_result, jim_m_String_to_string(jim_buf_String_get((jl_this)->f_buffer, jl_i)));
        } else {
            jl_result = jim_m_String_plus(jl_result, jim_m_String_plus(jim_m_String_to_string(jim_buf_String_get((jl_this)->f_buffer, jl_i)), rt_str_lit(", ", 2)));
        }
    }
    jl_result = jim_m_String_plus(jl_result, rt_str_lit("]", 1));
    return jl_result;
}

static void jim_m_Array_String__fill(jim_c_Array_String_* jl_this, jim_str jl_value) {
}

static void jim_m_Array_String__swap(jim_c_Array_String_* jl_this, int64_t jl_a, int64_t jl_b) {
}

static jim_c_Array_String_* jim_m_Array_String__clone(jim_c_Array_String_* jl_this) {
    return (jim_c_Array_String_*)NULL;
}

static jim_c_Array_String_* jim_m_Array_String__slice(jim_c_Array_String_* jl_this, int64_t jl_start, int64_t jl_end) {
    return (jim_c_Array_String_*)NULL;
}

static jim_c_Array_String_* jim_m_Array_String__concat(jim_c_Array_String_* jl_this, jim_c_Array_String_* jl_other) {
    return (jim_c_Array_String_*)NULL;
}

static jim_opt_bool jim_m_Array_String__is_empty(jim_c_Array_String_* jl_this) {
    return rt_opt_bool_none();
}

static jim_opt_bool jim_m_Array_String__equals(jim_c_Array_String_* jl_this, jim_c_Array_String_* jl_other) {
    return rt_opt_bool_none();
}

static void jim_m_Array_String__sort(jim_c_Array_String_* jl_this) {
}

static void jim_m_Array_String__reverse(jim_c_Array_String_* jl_this) {
}

static jim_c_Vector_String_* jim_m_Array_String__to_vector(jim_c_Array_String_* jl_this) {
    return (jim_c_Vector_String_*)NULL;
}

static int64_t jim_user_main(void) {
    jim_user_print(rt_str_lit("hello from jim", 14));
    jim_c_Vector_Integer_* jl_v = ({ jim_c_Vector_Integer_* jim_lit = jim_new_Vector_Integer_(); jim_m_Vector_Integer__push(jim_lit, INT64_C(1)); jim_m_Vector_Integer__push(jim_lit, INT64_C(2)); jim_m_Vector_Integer__push(jim_lit, INT64_C(3)); jim_m_Vector_Integer__push(jim_lit, INT64_C(4)); jim_lit; });
    int64_t jl_sum = INT64_C(0);
    {
        jim_c_Vector_Integer_* jl___jim_it_7_5 = jl_v;
        for (int64_t jl___jim_i_7_5 = INT64_C(0); jim_m_Integer_less_than(jl___jim_i_7_5, jim_m_Vector_Integer__length(jl___jim_it_7_5)); jl___jim_i_7_5 = jim_m_Integer_plus(jl___jim_i_7_5, INT64_C(1))) {
            int64_t jl_x = jim_m_Vector_Integer__get(jl___jim_it_7_5, jl___jim_i_7_5);
            jl_sum = jim_m_Integer_plus(jl_sum, jl_x);
        }
    }
    jim_user_print(jim_m_String_plus(rt_str_lit("sum = ", 6), jim_m_Integer_to_string(jl_sum)));
    return INT64_C(0);
    return INT64_C(0);
}

static void jim_user_print(jim_str jl_s) {
    rt_print_string(jl_s);
}

static jim_opt_str jim_user_input(void) {
    return rt_opt_str_none();
}

static void jim_user_print_err(jim_str jl_msg) {
}

static jim_opt_str jim_user_read_file(jim_str jl_file) {
    return rt_opt_str_none();
}

static jim_opt_i64 jim_user_write_file(jim_str jl_file, jim_str jl_content) {
    return rt_opt_i64_none();
}

static jim_opt_i64 jim_user_append_file(jim_str jl_file, jim_str jl_content) {
    return rt_opt_i64_none();
}

static jim_opt_bool jim_user_file_exists(jim_str jl_file) {
    return rt_opt_bool_none();
}

int main(void) {
    rt_init();
    int64_t jim_exit_code = jim_user_main();
    rt_shutdown();
    return (int)jim_exit_code;
}
