#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    // literals & names
    Int(i64),
    Float(f64),
    Str(String),
    CharLit(u8), // a jim Char is one byte
    Ident(String),
    Intrinsic(String), // @name

    // keywords
    KwFunction,
    KwVar,
    KwConst,
    KwIf,
    KwElse,
    KwFor,
    KwWhile,
    KwIn,
    KwBreak,
    KwContinue,
    KwReturn,
    KwClass,
    KwPublic,
    KwPrivate,
    KwThis,
    KwTrue,
    KwFalse,
    KwNone,
    KwAnd,
    KwOr,
    KwNot,
    KwDiv,
    KwTry,
    KwCatch,
    KwImport, // lexed from "#import"

    // punctuation
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Comma,
    Semicolon,
    Colon,
    Dot,
    Question,
    Ampersand,
    Arrow, // ->

    // operators
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    PlusPlus,
    MinusMinus,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    Assign,
    EqEq,
    NotEq,
    Lt,
    LtEq,
    Gt,
    GtEq,

    Eof,
}

impl TokenKind {
    /// Human-readable name for diagnostics.
    pub fn describe(&self) -> String {
        match self {
            TokenKind::Int(v) => format!("integer literal {}", v),
            TokenKind::Float(v) => format!("float literal {}", v),
            TokenKind::Str(_) => "string literal".to_string(),
            TokenKind::CharLit(_) => "char literal".to_string(),
            TokenKind::Ident(n) => format!("'{}'", n),
            TokenKind::Intrinsic(n) => format!("'@{}'", n),
            TokenKind::KwFunction => "'function'".to_string(),
            TokenKind::KwVar => "'var'".to_string(),
            TokenKind::KwConst => "'const'".to_string(),
            TokenKind::KwIf => "'if'".to_string(),
            TokenKind::KwElse => "'else'".to_string(),
            TokenKind::KwFor => "'for'".to_string(),
            TokenKind::KwWhile => "'while'".to_string(),
            TokenKind::KwIn => "'in'".to_string(),
            TokenKind::KwBreak => "'break'".to_string(),
            TokenKind::KwContinue => "'continue'".to_string(),
            TokenKind::KwReturn => "'return'".to_string(),
            TokenKind::KwClass => "'class'".to_string(),
            TokenKind::KwPublic => "'public'".to_string(),
            TokenKind::KwPrivate => "'private'".to_string(),
            TokenKind::KwThis => "'this'".to_string(),
            TokenKind::KwTrue => "'true'".to_string(),
            TokenKind::KwFalse => "'false'".to_string(),
            TokenKind::KwNone => "'None'".to_string(),
            TokenKind::KwAnd => "'and'".to_string(),
            TokenKind::KwOr => "'or'".to_string(),
            TokenKind::KwNot => "'not'".to_string(),
            TokenKind::KwDiv => "'div'".to_string(),
            TokenKind::KwTry => "'try'".to_string(),
            TokenKind::KwCatch => "'catch'".to_string(),
            TokenKind::KwImport => "'#import'".to_string(),
            TokenKind::LParen => "'('".to_string(),
            TokenKind::RParen => "')'".to_string(),
            TokenKind::LBrace => "'{'".to_string(),
            TokenKind::RBrace => "'}'".to_string(),
            TokenKind::LBracket => "'['".to_string(),
            TokenKind::RBracket => "']'".to_string(),
            TokenKind::Comma => "','".to_string(),
            TokenKind::Semicolon => "';'".to_string(),
            TokenKind::Colon => "':'".to_string(),
            TokenKind::Dot => "'.'".to_string(),
            TokenKind::Question => "'?'".to_string(),
            TokenKind::Ampersand => "'&'".to_string(),
            TokenKind::Arrow => "'->'".to_string(),
            TokenKind::Plus => "'+'".to_string(),
            TokenKind::Minus => "'-'".to_string(),
            TokenKind::Star => "'*'".to_string(),
            TokenKind::Slash => "'/'".to_string(),
            TokenKind::Percent => "'%'".to_string(),
            TokenKind::PlusPlus => "'++'".to_string(),
            TokenKind::MinusMinus => "'--'".to_string(),
            TokenKind::PlusEq => "'+='".to_string(),
            TokenKind::MinusEq => "'-='".to_string(),
            TokenKind::StarEq => "'*='".to_string(),
            TokenKind::SlashEq => "'/='".to_string(),
            TokenKind::Assign => "'='".to_string(),
            TokenKind::EqEq => "'=='".to_string(),
            TokenKind::NotEq => "'!='".to_string(),
            TokenKind::Lt => "'<'".to_string(),
            TokenKind::LtEq => "'<='".to_string(),
            TokenKind::Gt => "'>'".to_string(),
            TokenKind::GtEq => "'>='".to_string(),
            TokenKind::Eof => "end of file".to_string(),
        }
    }
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub line: u32,
    pub col: u32,
}
